r"""
P.E.T.E.R. — Install mobile backend auto-start (Windows only).

Run ONCE with:
    python install_autostart.py

This registers the mobile backend (and Peter's voice worker) to launch
automatically at Windows login, running in the background with no window.
After that, whenever your PC is on, the phone site
    http://<THIS_PC_LAN_IP>:9094
just works — no need to open the desktop app or start anything manually.

It adds a "PETER-Mobile" entry to the registry Run key that launches a tiny
silent WSH `.vbs` launcher (created next to this script). The launcher:

  1.  `cd`s into the project directory (Windows Run-key entries start with the
      working directory set to %windir%\System32, which would make relative
      `.env` / module paths fail);
  2.  runs `<venv>\Scripts\pythonw.exe mobile_backend.py` with no console
      window (pythonw.exe guarantees no black flash).

Re-run anytime to update. To remove it later, run:
    python install_autostart.py --remove
"""

from __future__ import annotations

import os
import sys
import winreg

_LAUNCHER_NAME = "peter_mobile_autostart.vbs"


def _project_dir() -> str:
    return os.path.dirname(os.path.abspath(__file__))


def _backend_pythonw() -> str:
    """Return the venv's pythonw.exe (no console window)."""
    base = _project_dir()
    for sub in (".venv", "venv"):
        candidate = os.path.join(base, sub, "Scripts", "pythonw.exe")
        if os.path.exists(candidate):
            return candidate
    raise FileNotFoundError(
        "Could not find pythonw.exe in .venv or venv. "
        "Run the backend manually with `python mobile_backend.py` instead."
    )


def _launcher_path() -> str:
    return os.path.join(_project_dir(), _LAUNCHER_NAME)


def _write_launcher() -> str:
    r"""Create a silent WSH launcher that runs the backend from the project dir.

    Windows Run-key entries always start with the working directory set to
    %windir%\System32 (the default). If we point the Run key straight at
    pythonw.exe + mobile_backend.py, the backend would start with the wrong
    CWD. That used to make `load_dotenv()` miss the project's `.env` file, so
    LIVEKIT_API_KEY / LIVEKIT_API_SECRET came back empty and the phone got a
    LiveKit token with no valid grants → the PWA froze with "could not reach
    Peter". This launcher fixes it by forcing the project directory as CWD.
    """
    project = _project_dir().replace("'", "''")
    pythonw = _backend_pythonw().replace("'", "''")
    backend = os.path.join(project, "mobile_backend.py").replace("'", "''")

    vbs = (
        "' P.E.T.E.R. mobile backend autostart launcher (generated by install_autostart.py)\n"
        "Set sh = CreateObject(\"WScript.Shell\")\n"
        f"sh.CurrentDirectory = \"{project}\"\n"
        f"sh.Run \"\"\"{pythonw}\"\" \"\"\"{backend}\"\"\", 0, False\n"
    )
    path = _launcher_path()
    with open(path, "w", encoding="utf-8") as f:
        f.write(vbs)
    return path


def install() -> str:
    launcher = _write_launcher()

    # Command: wscript.exe <launcher.vbs>  (silent, sets correct CWD)
    cmd = f'wscript.exe "{launcher}"'

    key = winreg.OpenKey(
        winreg.HKEY_CURRENT_USER,
        r"Software\Microsoft\Windows\CurrentVersion\Run",
        0,
        winreg.KEY_SET_VALUE,
    )
    try:
        winreg.SetValueEx(key, "PETER-Mobile", 0, winreg.REG_SZ, cmd)
    finally:
        winreg.CloseKey(key)
    return cmd


def remove() -> None:
    key = winreg.OpenKey(
        winreg.HKEY_CURRENT_USER,
        r"Software\Microsoft\Windows\CurrentVersion\Run",
        0,
        winreg.KEY_SET_VALUE,
    )
    try:
        try:
            winreg.DeleteValue(key, "PETER-Mobile")
        except FileNotFoundError:
            print("  No PETER-Mobile startup entry found (nothing to remove).")
    finally:
        winreg.CloseKey(key)
    # Remove the generated launcher too (best-effort).
    try:
        os.remove(_launcher_path())
    except OSError:
        pass
    print("  [OK] Removed PETER-Mobile autostart entry.")


if __name__ == "__main__":
    if "--remove" in sys.argv:
        print("P.E.T.E.R - removing autostart...")
        remove()
        sys.exit(0)

    print("P.E.T.E.R - installing mobile backend autostart...")
    try:
        cmd = install()
        print("  [OK] Registered 'PETER-Mobile' to start at login.")
        print(f"    Command: {cmd}")
        print()
        print("The mobile backend + Peter worker will now auto-start when you")
        print("log into Windows. Your phone link stays: http://<LAN_IP>:9094")
        print("(find your LAN IP when the backend first runs).")
    except Exception as e:  # noqa: BLE001
        print(f"ERROR: {e}")
        sys.exit(1)
