' P.E.T.E.R. mobile backend autostart launcher (generated by install_autostart.py)
Set sh = CreateObject("WScript.Shell")
sh.CurrentDirectory = "C:\Users\alope\OneDrive\Desktop\P.E.T.E.R"
sh.Run """C:\Users\alope\OneDrive\Desktop\P.E.T.E.R\.venv\Scripts\pythonw.exe"" """C:\Users\alope\OneDrive\Desktop\P.E.T.E.R\mobile_backend.py""", 0, False
